import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:url_launcher/url_launcher.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(PriceComparisonApp());
}

class PriceComparisonApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'X - Price Comparison App',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: HomePage(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final TextEditingController _searchController = TextEditingController();
  final TextEditingController _pincodeController = TextEditingController();
  String userPincode = "";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Compare Prices')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            TextField(
              controller: _searchController,
              decoration: InputDecoration(
                hintText: 'Search for a product (e.g., Tea Cup)',
                border: OutlineInputBorder(),
                suffixIcon: Icon(Icons.search),
              ),
            ),
            SizedBox(height: 12),
            TextField(
              controller: _pincodeController,
              keyboardType: TextInputType.number,
              decoration: InputDecoration(
                hintText: 'Enter your pincode',
                border: OutlineInputBorder(),
                suffixIcon: IconButton(
                  icon: Icon(Icons.check),
                  onPressed: () {
                    setState(() {
                      userPincode = _pincodeController.text;
                    });
                  },
                ),
              ),
            ),
            SizedBox(height: 20),
            Text(
              'Sample Product Result:',
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
            ),
            SizedBox(height: 10),
            Expanded(
              child: ListView(
                children: [
                  ProductComparisonCard(
                    imageUrl: 'https://via.placeholder.com/150',
                    title: 'Modern Ceramic Tea Cup',
                    sellers: [
                      SellerInfo(name: 'Amazon', price: '₹249', delivery: '2-3 Days', rating: '4.3', coupon: 'AMZ10', min: '₹199', max: '₹299', predict: '₹269', affiliateUrl: 'https://amzn.to/example1'),
                      SellerInfo(name: 'Flipkart', price: '₹259', delivery: '3-5 Days', rating: '4.2', coupon: 'FKT15', min: '₹209', max: '₹289', predict: '₹279', affiliateUrl: 'https://fkrt.it/example2'),
                      SellerInfo(name: 'Meesho', price: '₹235', delivery: '5-7 Days', rating: '4.0', coupon: '', min: '₹199', max: '₹279', predict: '₹250', affiliateUrl: 'https://meesho.link/example3'),
                    ],
                    userPincode: userPincode,
                  ),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}

class ProductComparisonCard extends StatelessWidget {
  final String imageUrl;
  final String title;
  final List<SellerInfo> sellers;
  final String userPincode;

  ProductComparisonCard({
    required this.imageUrl,
    required this.title,
    required this.sellers,
    required this.userPincode,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 3,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(12.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Image.network(imageUrl, width: 80, height: 80),
                Sized: 10),
                Expanded(
                  child: Text(title, style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                ),
              ],
            ),
            SizedBox(height: 10),
            Text('Compare from Sellers:', style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold)),
            ...sellers.map((seller) => SellerRow(seller: seller, pincode: userPincode)).toList(),
          ],
        ),
      ),
    );
  }
}

class SellerInfo {
  final String name;
  final String price;
  final String delivery;
  final String rating;
  final String coupon;
  final String min;
  final String max;
  final String predict;
  final String affiliateUrl;

  SellerInfo({
    required this.name,
    required this.price,
    required this.delivery,
    required this.rating,
    required this.coupon,
    required this.min,
    required this.max,
    required this.predict,
    required this.affiliateUrl,
  });
}

class SellerRow extends StatelessWidget {
  final SellerInfo seller;
  final String pincode;

  SellerRow({required this.seller, required this.pincode});

  Future<Uri> createDynamicLink(String productId, String url) async {
    final DynamicLinkParameters parameters = DynamicLinkParameters(
      uriPrefix: 'https://yourcustomprefix.page.link',
      link: Uri.parse('https://yourapp.com/product?id=$productId&redirect=$url'),
      androidParameters: AndroidParameters(
        packageName: 'com.yourcompany.yourapp',
        minimumVersion: 1,
      ),
      iosParameters: IOSParameters(
        bundleId: 'com.yourcompany.yourapp',
        minimumVersion: '1.0.1',
        appStoreId: '123456789',
      ),
    );

    final ShortDynamicLink shortLink = await FirebaseDynamicLinks.instance.buildShortLink(parameters);
    return shortLink.shortUrl;
  }

  void launchUrl(Uri url) async {
    if (await canLaunch(url.toString())) {
      await launch(url.toString());
    } else {
      throw 'Could not launch $url';
    }
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      color: Colors.grey.shade100,
      margin: EdgeInsets.symmetric(vertical: 6),
      child: ListTile(
        title: Text(seller.name, style: TextStyle(fontWeight: FontWeight.bold)),
        subtitle: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Price: ${seller.price} | Delivery: ${seller.delivery} | Rating: ${seller.rating}'),
            Text('Price Stats - Min: ${seller.min}, Max: ${seller.max}, Predict: ${seller.predict}'),
            if (seller.coupon.isNotEmpty) Text('Coupon: ${seller.coupon}', style: TextStyle(color: Colors.green)),
            if (pincode.isNotEmpty) Text('Est. Delivery for $pincode: ${seller.delivery}', style: TextStyle(color: Colors.blue)),
          ],
        ),
        trailing: ElevatedButton(
          onPressed: () async {
            final dynamicUrl = await createDynamicLink('product123', seller.affiliateUrl);

            final FirebaseAnalytics analytics = FirebaseAnalytics.instance;
            await analytics.logEvent(
              name: 'click_seller',
              parameters: {
                'product_id': 'product123',
                'seller': seller.name,
                'pincode': pincode,
                'price': seller.price,
              },
            );

            launchUrl(dynamicUrl);
          },
          child: Text('Buy Now'),
        ),
      ),
    );
  }
}
