workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    environment:
      flutter: stable
    scripts:
      - name: Install Dependencies
        script: flutter pub get

      - name: Run Tests (optional)
        script: flutter test

      - name: Build Release APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
