workflows:
  build-android:
    name: Build Flutter App from Subfolder
    environment:
      flutter: stable
    scripts:
      - name: Move to subfolder
        script: cd Mani_first

      - name: Install dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - Mani_first/build/app/outputs/flutter-apk/app-release.apk
