workflows:
  build-android:
    name: Build Flutter App from Subfolder
    environment:
      flutter: stable
    scripts:
      - name: Install & Build from subfolder
        script: |
          cd Mani_first
          flutter pub get
          flutter build apk --release

    artifacts:
      - Mani_first/build/app/outputs/flutter-apk/app-release.apk

